- name: Copy static files
  copy:
    src: ./
    dest: "{{ fiw_path }}"

- name: Copy theme
  copy:
    src: "{{ playbook_dir }}/themes/{{ fiw_theme }}"
    dest: "{{ fiw_path }}/themes"
  when: fiw_theme != "default"

- name: "create {{ fiw_path }}/build"
  file:
    path: "{{ fiw_path }}/build"
    state: directory

- name: Build main.js
  template:
    src: ../templates/main.js
    dest: "{{ fiw_path }}/js/main-tmp.js"

- name: Build html page
  template:
    src: ../templates/index.html
    dest: "{{ fiw_path }}/index.html"
